# Generated by Django 5.0.6 on 2024-06-10 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('posting_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=60)),
                ('cancel_reason_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('in_process_at', models.DateTimeField(blank=True, null=True)),
                ('shipment_date', models.DateTimeField(blank=True, null=True)),
                ('sku', models.CharField(max_length=50)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('offer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mandatory_mark', models.TextField(blank=True, null=True)),
                ('barcodes', models.TextField(blank=True, null=True)),
                ('analytics_data', models.TextField(blank=True, null=True)),
                ('financial_data', models.TextField(blank=True, null=True)),
                ('is_fraud', models.BooleanField(default=False)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
