# Generated by Django 5.0.6 on 2024-06-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('order_number', models.CharField(max_length=255, null=True)),
                ('posting_number', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('cancel_reason_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField()),
                ('in_process_at', models.DateTimeField()),
                ('shipment_date', models.DateTimeField()),
                ('sku', models.BigIntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('offer_id', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mandatory_mark', models.CharField(max_length=255, null=True)),
                ('barcodes', models.TextField(null=True)),
                ('analytics_data', models.TextField(null=True)),
                ('financial_data', models.TextField(null=True)),
                ('is_fraud', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
