# Generated by Django 5.0.6 on 2024-06-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cy19346_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='posting_number',
            field=models.CharField(default='""', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
