# Generated by Django 5.0.6 on 2024-06-28 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cy19346_project', '0005_delete_apikey_alter_order_posting_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='posting_number',
            field=models.CharField(default='null', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_keys',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
